openapi: 3.0.1
info:
  title: ViaCEP
  description: Consulte CEPs de todo o Brasil.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  url: https://viacep.com.br/
tags:
  name: Address
  description: Getting zip-code informations
  externalDocs:
    description: Find out more
    url: http://swagger.io
x-kong-key-auth:
  name: key-auth
  enabled: true
  config:
    run_on_preflight: true
    hide_credentials: false
    key_in_body: false
    key_in_query: true
    key_in_header: true
    key_names:
      - apikey
paths:
  /ws/zip-code/json:
    get:
      tags: Address
      summary: Find Address by zip-code
      description: Returns a single Address
      operationId: getAddressByzip-code
      parameters:
        name: zip-code
        in: path
        description: zip-code to search
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: null
        '400':
          description: Invalid zip-code supplied
          content: null
        '404':
          description: Address not found
          content: null
components:
  schemas:
    Address:
      type: object
      properties:
        cep:
          type: string
        logradouro:
          type: string
        complemento:
          type: string
        bairro:
          type: string
        localidade:
          type: string
        uf:
          type: string
        ibge:
          type: string
        gia:
          type: string
        ddd:
          type: string
        siafi:
          type: string
