# openapi: 3.0.1
# info:
#   title: ViaCEP
#   description: Consulte CEPs de todo o Brasil.
#   termsOfService: http://swagger.io/terms/
#   contact:
#     email: apiteam@swagger.io
#   license:
#     name: Apache 2.0
#     url: http://www.apache.org/licenses/LICENSE-2.0.html
#   version: 1.0.0
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
# servers:
#   url: https://viacep.com.br/
# tags:
#   name: Address
#   description: Getting zip-code informations
#   externalDocs:
#     description: Find out more
#     url: http://swagger.io
# x-kong-rate-limiting:
#   name: rate-limiting
#   enabled: true
#   config:
#     redis_database: 0
#     redis_ssl_verify: false
#     limit_by: consumer
#     redis_port: 6379
#     policy: local
#     second: 8000
#     fault_tolerant: true
#     hide_client_headers: false
#     error_message: API rate limit exceeded
#     error_code: 429
#     redis_timeout: 2000
#     redis_ssl: false
#     sync_rate: -1
# paths:
#   /ws/zip-code/json:
#     get:
#       tags: Address
#       summary: Find Address by zip-code
#       description: Returns a single Address
#       operationId: getAddressByzip-code
#       parameters:
#         name: zip-code
#         in: path
#         description: zip-code to search
#         required: true
#         schema:
#           type: string
#       responses:
#         '200':
#           description: successful operation
#           content:
#             application/json:
#               schema:
#                 $ref: null
#         '400':
#           description: Invalid zip-code supplied
#           content: null
#         '404':
#           description: Address not found
#           content: null
# components:
#   schemas:
#     Address:
#       type: object
#       properties:
#         cep:
#           type: string
#         logradouro:
#           type: string
#         complemento:
#           type: string
#         bairro:
#           type: string
#         localidade:
#           type: string
#         uf:
#           type: string
#         ibge:
#           type: string
#         gia:
#           type: string
#         ddd:
#           type: string
#         siafi:
#           type: string
openapi: 3.0.0
info:
    description: 'app-exemple-platform-obs Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
    version: 1.0.2
    title: app-exemple-platform-obs
    termsOfService: http://swagger.io/terms/
    contact:
        email: apiteam@swagger.io
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
    - name: spec
      description: Health
      externalDocs:
        description: Find out more
        url: http://swagger.io
paths:
    /actuator/health:
        get:
            tags:
                - spec
            description: Health
            operationId: health
            responses:
                '200':
                    description: successful operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Health'
                '404':
                    description: health not found
servers:
    - url: https://petstore.swagger.io/v2
components:
    schemas:
        Health:
            type: object
            properties:
                status:
                    type: string
                    example: UP
